export const VALIDATE_COORDINATES_MAIN_FORM = "VALIDATE_COORDINATES_MAIN_FORM";
export const SET_X_VALUE_MAIN_FORM = "SET_X_VALUE_MAIN_FORM";
export const SET_Y_VALUE_MAIN_FORM = "SET_Y_VALUE_MAIN_FORM";
export const CHANGE_R_VALUE_MAIN_FORM = "CHANGE_R_VALUE_MAIN_FORM";

