export const SET_LOGIN_VALUE_SIGN_UP = "SET_LOGIN_VALUE_SIGN_UP";
export const SET_PASS_VALUE_SIGN_UP = "SET_PASS_VALUE_SIGN_UP";
export const VALIDATE_CREDENTIALS_SIGN_UP = "VALIDATE_CREDENTIALS_SIGN_UP";
export const SET_ERROR_SIGN_UP = "SET_ERROR_SIGN_UP";