export const SET_LOGIN_VALUE_SIGN_IN = "SET_LOGIN_VALUE_SIGN_IN";
export const SET_PASS_VALUE_SIGN_IN = "SET_PASS_VALUE_SIGN_IN";
export const VALIDATE_CREDENTIALS_SIGN_IN = "VALIDATE_CREDENTIALS_SIGN_IN";
export const SET_ERROR_SIGN_IN = "SET_ERROR_SIGN_IN";