export const SET_X_VALUE_CANVAS = "SET_X_VALUE_CANVAS";
export const SET_Y_VALUE_CANVAS = "SET_Y_VALUE_CANVAS";
export const SET_R_VALUE_CANVAS = "SET_R_VALUE_CANVAS";
export const VALIDATE_COORDINATES_CANVAS = "VALIDATE_COORDINATES_CANVAS";