version: '2'
services:
  postgresql:
    image: bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - 5432:5432

  keycloak:
    image: bitnami/keycloak:22
    depends_on:
      - postgresql
    ports:
      - 8081:8080

volumes:
  postgresql_data:
    driver: local
